name: "Azure Dev: Build and Deploy"

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [knowledgebot]

  # Allow manual workflow trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: "Development-ts"

    steps:
      - name: 🌱 Checkout to the branch
        uses: actions/checkout@v3

      - name: 🍏 Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install azd
        uses: Azure/setup-azd@v0.1.0

      - name: 🗝️ Azure Login
        run: |
          azd auth login --no-prompt --client-id "${{ vars.AZURE_AD_GITHUB_CLIENT_ID }}" --federated-credential-provider "github" --tenant-id "${{ vars.AZURE_TENANT_ID }}"

      - name: Package and deploy to Azure dev
        run: azd up --no-prompt
        env:
          AUTH_GITHUB_ID: ${{ vars.AUTH_GITHUB_ID }}
          AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}
          AZURE_ENV_NAME: ${{ vars.AZURE_ENV_NAME }}
          AZURE_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_INSTANCE_NAME: ${{ vars.AZURE_OPENAI_API_INSTANCE_NAME }}
          ADMIN_EMAIL_ADDRESS: ${{ vars.ADMIN_EMAIL_ADDRESS }}
          AUTH_ROLE: ${{ vars.AUTH_ROLE }}
          AZURE_AD_CLIENT_ID: ${{ vars.AZURE_AD_CLIENT_ID }}
          NEXTAUTH_URL: ${{ vars.NEXTAUTH_URL }}
          AZURE_AD_TENANT_ID: ${{ vars.AZURE_AD_TENANT_ID }}

          AZURE_AD_CLIENT_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}

          NEXT_PUBLIC_PACKAGE_JSON_URL: ${{ vars.NEXT_PUBLIC_PACKAGE_JSON_URL}}
